In [1]:
from datetime import datetime

import pandas as pd
import graphviz
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.dummy import DummyClassifier
from sklearn.svm import LinearSVC, SVC
from sklearn.tree import DecisionTreeClassifier, export_graphviz


uri = "https://gist.githubusercontent.com/guilhermesilveira/4d1d4a16ccbf6ea4e0a64a38a24ec884/raw/afd05cb0c796d18f3f5a6537053ded308ba94bf7/car-prices.csv"
data = pd.read_csv(uri, index_col=0)
data.head()

   mileage_per_year  model_year      price sold
0             21801        2000   30941.02  yes
1              7843        1998   40557.96  yes
2              7109        2006   89627.50   no
3             26823        2015   95276.14   no
4              7935        2014  117384.68  yes

In [2]:
data['sold'] = data['sold'].map({'yes': 1, 'no': 0})
data.head()

   mileage_per_year  model_year      price  sold
0             21801        2000   30941.02     1
1              7843        1998   40557.96     1
2              7109        2006   89627.50     0
3             26823        2015   95276.14     0
4              7935        2014  117384.68     1

In [3]:
data['model_age'] = datetime.today().year - data['model_year']
data.head()

   mileage_per_year  model_year      price  sold  model_age
0             21801        2000   30941.02     1         22
1              7843        1998   40557.96     1         24
2              7109        2006   89627.50     0         16
3             26823        2015   95276.14     0          7
4              7935        2014  117384.68     1          8

In [4]:
data['total_km'] = data['model_age'] * data['mileage_per_year'] * 1.60934
data.head()

   mileage_per_year  model_year      price  sold  model_age      total_km
0             21801        2000   30941.02     1         22  771874.86948
1              7843        1998   40557.96     1         24  302929.28688
2              7109        2006   89627.50     0         16  183052.76896
3             26823        2015   95276.14     0          7  302171.28774
4              7935        2014  117384.68     1          8  102160.90320

In [5]:
del data['mileage_per_year']
del data['model_year']

data.head()

       price  sold  model_age      total_km
0   30941.02     1         22  771874.86948
1   40557.96     1         24  302929.28688
2   89627.50     0         16  183052.76896
3   95276.14     0          7  302171.28774
4  117384.68     1          8  102160.90320

In [6]:
X = data[['price', 'model_age', 'total_km']]
Y = data['sold']

In [7]:
SEED = 5

In [8]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, stratify=Y, random_state=SEED, test_size=0.25)

clf_linear_svc = LinearSVC(random_state=SEED)
clf_linear_svc.fit(X_train, Y_train)

accuracy = clf_linear_svc.score(X_test, Y_test)
print('Precisão Linear SVC: %.2f%%' % (accuracy * 100))

Precisão Linear SVC: 58.00%

/opt/conda/lib/python3.10/site-packages/sklearn/svm/_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

In [9]:
baseline_stratified = DummyClassifier(random_state=SEED)
baseline_stratified.fit(X_train, Y_train)

accuracy = baseline_stratified.score(X_test, Y_test)
print('Precisão Stratified: %.2f%%' % (accuracy * 100))

Precisão Stratified: 58.00%

In [10]:
baseline_most_frequent = DummyClassifier(strategy='most_frequent', random_state=SEED)
baseline_most_frequent.fit(X_train, Y_train)

accuracy = baseline_most_frequent.score(X_test, Y_test)
print('Precisão Most Frequent: %.2f%%' % (accuracy * 100))

Precisão Most Frequent: 58.00%

In [11]:
raw_X_train, raw_X_test, Y_train, Y_test = train_test_split(X, Y, stratify=Y, random_state=SEED, test_size=0.25)

scaler = StandardScaler()
X_train = scaler.fit_transform(raw_X_train)
X_test = scaler.transform(raw_X_test)

clf_svc = SVC(gamma='auto', random_state=SEED)
clf_svc.fit(X_train, Y_train)

accuracy = clf_svc.score(X_test, Y_test)
print('Precisão SVC: %.2f%%' % (accuracy * 100))

Precisão SVC: 77.60%

In [12]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, stratify=Y, random_state=SEED, test_size=0.25)

clf_decision_tree = DecisionTreeClassifier(random_state=SEED, max_depth=3)
clf_decision_tree.fit(X_train, Y_train)

accuracy = clf_decision_tree.score(X_test, Y_test)
print('Precisão Decision Tree: %.2f%%' % (accuracy * 100))

Precisão Decision Tree: 79.28%

In [13]:
dot_data = export_graphviz(clf_decision_tree, out_file=None, feature_names=X.columns, filled=True, rounded=True, class_names=['não', 'sim'])
graph = graphviz.Source(dot_data)
graph